# Generated by Django 5.1.7 on 2025-03-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_image_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_style',
            field=models.CharField(default='adventurer', max_length=50),
        ),
    ]
