# Generated by Django 5.1.5 on 2025-04-07 19:53

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_info_profile_about_remove_profile_displayname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='avatar.png', null=True, upload_to=accounts.models.user_avatar_upload_path),
        ),
    ]
