# Generated by Django 5.1.5 on 2025-05-07 14:31

import admin_dashboard.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_availability_daytemplate_alter_adminprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='admin_default.png', storage=django.core.files.storage.FileSystemStorage(base_url='/media/profiles/', location='media\\profiles'), upload_to=admin_dashboard.models.admin_profile_picture_path),
        ),
    ]
