# Generated by Django 5.1.5 on 2025-04-29 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('override_hours', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.AddField(
            model_name='appointment',
            name='contact_method',
            field=models.CharField(choices=[('zoom', 'Zoom'), ('phone', 'Phone Call'), ('whatsapp', 'WhatsApp Call')], default='zoom', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='custom_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='appointment',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.CharField(choices=[('branding', 'Branding and Consultancy'), ('marketing', 'Digital Marketing'), ('social_media', 'Social Media Management'), ('graphics', 'Graphics Design'), ('web_dev', 'Website and App Development'), ('auditing', 'Account Auditing'), ('customer_service', 'Customer Service Optimization'), ('hr_management', 'Human Resources Management'), ('financial_advisory', 'Funding and Financial Advisory'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='timezone',
            field=models.CharField(default='WAT', max_length=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='whatsapp_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='availability',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.availability'),
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='appointments.availability')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='timeslot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.timeslot'),
        ),
    ]
