# Generated by Django X.Y on YYYY-MM-DD HH:MM
from django.db import migrations, models
import django.utils.timezone

class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_availability_remove_appointment_client_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='override_hours',
            new_name='override_template',
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]