# Generated by Django 5.1.5 on 2025-05-01 16:09

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_add_end_times'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], unique=True)),
                ('is_available', models.BooleanField(default=True)),
                ('start_time', models.TimeField(default=datetime.time(9, 0))),
                ('end_time', models.TimeField(default=datetime.time(17, 0))),
            ],
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['timeslot__availability__date', 'timeslot__time']},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['time']},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='availability',
        ),
        migrations.AddField(
            model_name='availability',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='contact_method',
            field=models.CharField(choices=[('zoom', 'Zoom'), ('phone', 'Phone Call'), ('whatsapp', 'WhatsApp Call')], max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.CharField(choices=[('branding', 'Branding and Consultancy'), ('marketing', 'Digital Marketing'), ('social_media', 'Social Media Management'), ('graphics', 'Graphics Design'), ('web_dev', 'Website and App Development'), ('auditing', 'Account Auditing'), ('customer_service', 'Customer Service Optimization'), ('hr_management', 'Human Resources Management'), ('financial_advisory', 'Funding and Financial Advisory'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='appointments.timeslot'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('availability', 'time')},
        ),
    ]
