# Generated by Django 5.1.5 on 2025-05-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_daytemplate_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daytemplate',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='daytemplate',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
